FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine

RUN apk add --no-cache \
    bash \
    ripgrep

COPY --from=ghcr.io/anomalyco/opencode@sha256:0d3c9551ea2522fcfd23fbc2e302fc87218d6c198bff277e8ab44d93a3bd6d3d \
    /usr/local/bin/opencode \
    /usr/local/bin/opencode

ENTRYPOINT ["opencode"]